### ISSUE TITLE
No MDF File

### ISSUE THREAD

**Issue by MedAkou** [Frost-06/water-billing-management-system#2]
Hi.
I enjoyed your presentation however there is no AquatricDatabase.MDF file to run the app.

Can you put it up here?
Many thanks

**Comment by Frost-06** [comment]
Hello,

Sorry for the late reply. I'm kinda busy lately will upload it later

**Comment by Frost-06** [comment]
Hi MedAkou,

Sorry for the late reply, I cant upload the mdf file due to GitHub
restrictions. I'll just send it to you here directly to this link.

Enjoy happy coding!

Kind regards,
Andre



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
22-06-05,
10:43:54 p.m.

**Comment by Nujoma** [comment]
Hi,
I have liked your system presentation but was unable to run it because of lack of the .MDF file. Any chance I could have it to try out the system?
Thanks
